spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${BANK_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
